windows:
  2:
    name: apache2
    command: |
      while true; do
        LD_LIBRARY_PATH=/opt/local/apache2/modules/ /opt/local/apache2/bin/apachectl -d reverse-proxy -e info -DFOREGROUND;
      done
  7:
    name: test
