# If you do not have OpenSSL installed, update
# the following line to use "http://" instead
source 'https://rubygems.org'

gem 'haml'
gem 'activesupport'
gem 'addressable'
gem 'capybara'
gem 'faker'
gem 'faraday'
gem 'git'
gem 'json_roa-client', '=2.0.0.pre.beta.5'
# gem 'json_roa-client', path: '/Users/thomas/Programming/JSON-ROA/ruby_client'
gem 'poltergeist'
gem 'pry'
gem 'rb-readline'
gem 'rest-client'
gem 'rspec'
gem 'rubocop'
gem 'selenium-webdriver'
gem 'sinatra'
