traits:
  PostgreSQL 10: true

scripts:

  create-database:
    body: |
      #!/usr/bin/env bash
      set -euo pipefail
      source integration-tests/cider-ci/bin/pg_env_set
      createdb "cider-ci_test_${CIDER_CI_TRIAL_ID}"

  migrate-database:
    start_when:
      the database has been created:
        script_key: create-database
      cider-ci has been compiled:
        script_key: compile_cider-ci
    body: |
      #!/usr/bin/env bash
      set -euo pipefail
      source integration-tests/cider-ci/bin/pg_env_set
      server/bin/env/java-setup
      java -jar server/target/cider-ci.jar \
        server migrate \
        -d "jdbc:postgresql://${PGUSER}:${PGPASSWORD}@localhost:${PGPORT}/cider-ci_test_${CIDER_CI_TRIAL_ID}"

  delete-database:
    body: |
      #!/usr/bin/env bash
      set -euo pipefail
      source integration-tests/cider-ci/bin/pg_env_set
      dropdb "cider-ci_test_${CIDER_CI_TRIAL_ID}"
    ignore_state: true
    start_when:
      include: cider-ci/shared/test_is_terminal.yml
      'the database has been created':
        script_key: create-database
        states: [passed]

