### configure

traits:
  Ruby: true

scripts:
  configure-server:
    body: |
      #!/usr/bin/ruby
      require 'yaml'
      config = YAML.load_file 'config/config_default.yml'

      # secrets

      config['basic_auth']['password'] = ENV['SERVICES_SECRET']
      config['secret'] = ENV['MASTER_SECRET']

      # database
      config['database']['user']= ENV['PGUSER']
      config['database']['password']= ENV['PGPASSWORD']
      config['database']['subname']= "//localhost:#{ENV['PGPORT']}/cider-ci_test_#{ENV['CIDER_CI_TRIAL_ID']}"

      config['server_base_url']= "http://localhost:#{ENV['REVERSE_PROXY_HTTP_PORT']}"

      # server
      config['services']['server']['http']['port']= Integer(ENV['SERVER_HTTP_PORT'])
      config['services']['server']['nrepl']['enabled']= false

      # ui
      config['services']['ui']['http']['port']= Integer(ENV['UI_HTTP_PORT'])

      # extended server UI for tests
      config['repository_service_advanced_api_edit_fields'] = true

      # WRITE Config ############################################################
      File.open('config/config_default.yml','w') { |file| file.write config.to_yaml }
      File.open('config/config.yml','w') { |file| file.write config.to_yaml }
