jobs:
  Integration-Tests:
    description: |
      This job must be run from the master project Cider-CI!

    run-on:
    - type: branch
      include-match: ^.*$

    context:

      subcontexts:
        _cider-ci_include:
          - cider-ci/subcontexts/service-tests.yml
